item {
    id: 1
    name: 'bun'
}
item {
    id: 2
    name: 'mayonaise'
}
item {
    id: 3
    name: 'ketchup'
}
item {
    id: 4
    name: 'tomatoes'
}
item {
    id: 5
    name: 'lettuce'
}
item {
    id: 6
    name: 'beef_patty'
}
item {
    id: 7
    name: 'cheese'
}
item {
    id: 8
    name: 'mustard'
}
item {
    id: 9
    name: 'bun_top'
}
item {
    id: 10
    name: 'onions'
}